language: node_js
node_js: '8'
cache: npm
notifications:
  email: false
script:
  - npm run test:prod && npm run build
jobs:
  include:
    - stage: deploy docs
      node_js: '8'
      script: npm run build
      deploy:
        local-dir: docs
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
