language: node_js
node_js: '8'
cache: npm
notifications:
  email: false
jobs:
  include:
  - stage: test
    script:
    - npm run test:prod
  - stage: deploy
    name: 'deploy docs'
    script: npm run build
    deploy:
      provider: pages
      local-dir: docs
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        tags: true
        branch: master
        repo: hyrsky/pankkiyhteys
  - script: npm run build
    name: 'deploy npm package'
    deploy:
      provider: npm
      skip_cleanup: true
      email: santeri@oikeuttaelaimille.fi
      api_key: "$NPM_TOKEN"
      on:
        tags: true
        repo: hyrsky/pankkiyhteys
