name: Build

on:
  push:
    branches: [boltworks-pankkiyhteys-main]
  pull_request:
    branches: [boltworks-pankkiyhteys-main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - name: Create package output
        uses: actions/upload-artifact@v4
        with:
          name: pankkiyhteys package
          path: pankkiyhteys-*.tgz
